# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages


name: Node.js CI

on:
  push:
    branches: [main]

jobs:
  build:
    defaults:
      run:
        working-directory: ./back-end
    runs-on: ${{ matrix.os }} #ubuntu-latest

    strategy:
      matrix:
        os: [ubuntu-latest] # macos-latest, windows-latest
        node-version: [16.x]
        #See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:

      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - shell: bash
        env:
        MONGO_DB: ${{ secrets.MONGO_DB }}
        MONGO_USER: ${{ secrets.MONGO_USER }}
        MONGO_PWD: ${{ secrets.MONGO_PWD }}
        MONGO_CLUSTER: ${{ secrets.MONGO_CLUSTER }}
      - run: npm ci # similar to npm install
      - run: npm run build --if-present
      - run: npm test
